spring.application.name=tgcompliment_bot

# Server configuration
server.port=8080

# Telegram Bot configuration
telegram.bot.token=8228027755:AAEOxwTwvWtYuCNxzeLxF9flFzDoRR-LvnI
telegram.bot.username=student_buster_bot

# Logging (???????????)
logging.level.com.example.tgcompliment_bot=DEBUG
logging.level.org.telegram=INFO